version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ec2
    container_name: insta-auto-ai-post
    restart: on-failure:0
    environment:
      - AWS_REGION=il-central-1
      - AWS_DEFAULT_REGION=il-central-1
      - INSTAGRAM_SESSION_FILE=/app/session.json
    volumes:
      - ./session.json:/app/session.json
      - ./locks:/app/locks
      - ./logs:/app/logs
